### ISSUE TITLE
Valikko katoaa skrollatessa mobiililla alaspäin

### ISSUE THREAD

**Issue by knomepasi** [Ropecon/ropecon-www#23]

**Comment by knomepasi** [comment]
Avataan uudelleen, bugi toistuu vielä iPhone (iOS 15.6) ja iPad Mini 6 (iPadOS 16 (Beta 1))

**Comment by tnli** [comment]
Tämä bugi myös androidissa, OnePlus Nord N10 5G (tjsp) Android 11/Chrome 103. Muistelisin et olis ollut myös 2018 tai 2019 kun tuo samalta näyttävä leiska otettiin käyttöön. Workaroundina tuollahan on sivun alareunassa sama valikko.

**Comment by knomepasi** [comment]
Pitäisi olla lopullisesti korjattu commitissa 5342661727fc4b48fa25ffbd8d04c668dbf1dacc

**Comment by knomepasi** [comment]
Ongelma ei toistaiseksi ole toistunut 0ade5cbe632b563edf4523e41a991e27a006638a jälkeen, suljetaan
